NAME = libft.a

MY_SOURCES = ft_atoi.c\
			 ft_bzero.c\
			 ft_calloc.c\
			 ft_isalnum.c\
			 ft_isalpha.c\
			 ft_isascii.c\
			 ft_isdigit.c\
			 ft_isprint.c\
			 ft_itoa.c\
			 ft_memchr.c\
			 ft_memcmp.c\
			 ft_memcpy.c\
			 ft_memmove.c\
			 ft_memset.c\
			 ft_putchar_fd.c\
			 ft_putendl_fd.c\
			 ft_putnbr_fd.c\
			 ft_putstr_fd.c\
			 ft_split.c\
			 ft_strchr.c\
			 ft_strdup.c\
			 ft_striteri.c\
			 ft_strjoin.c\
			 ft_strlcat.c\
			 ft_strlcpy.c\
			 ft_strlen.c\
			 ft_strmapi.c\
			 ft_strncmp.c\
			 ft_strnstr.c\
			 ft_strtrim.c\
			 ft_strrchr.c\
			 ft_substr.c\
			 ft_tolower.c\
			 ft_toupper.c\
			 ft_printf.c\
			 utilis.c\
			 ft_strjoin_with.c\
			 ft_strjoin_with_env.c\
			 put_fd.c\
			 ft_strcmp.c\
			 ft_lstadd_back.c\
			 ft_lstadd_front.c\
			 ft_lstclear.c\
			 ft_lstdelone.c\
			 ft_lstiter.c\
			 ft_lstlast.c\
			 ft_lstmap.c\
			 ft_lstnew.c\
			 ft_lstsize.c\
			
# BONUS_SRCS = ft_lstnew.c\
# 			 ft_lstadd_front.c\
# 			 ft_lstsize.c\
# 			 ft_lstlast.c\
# 			 ft_lstadd_back.c\
# 			 ft_lstdelone.c\
# 			 ft_lstclear.c\
# 			 ft_lstiter.c\
# 			 ft_lstmap.c\
			 

OBJECTS = $(MY_SOURCES:.c=.o)

# BONUS_OBJECTS = $(BONUS_SRCS:.c=.o)

HEADER = ../headers

COMPILER = cc

CFLAGS = -Wall -Wextra -Werror -I$(HEADER)

RM = rm -f

LIBC = ar rcs

all: $(NAME)

$(NAME): $(OBJECTS)
	$(LIBC) $(NAME) $(OBJECTS)

bonus: $(OBJECTS)
	$(LIBC) $(NAME) 

%.o: %.c
	$(COMPILER) $(CFLAGS) -c $< -o $@

clean:
	$(RM) $(OBJECTS)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean bonus re
